source:
  docker_image: "airbyte/source-github:latest"  # Not used since we're using PyPI
  config:
    credentials:
      option_title: "PAT Credentials"
      personal_access_token: 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  # Your GitHub Personal Access Token
    repositories:
      - your-org/your-repo  # e.g., pathwaycom/pathway
    api_url: "https://api.github.com/"
  streams: commits  # What to ingest
